(() => {
  'use strict';
  const $=s=>document.querySelector(s), C=BookCore;
  let db, records=[], pet=C.profile({name:'她',subtitle:'有些陪伴，成为了我们生命里永远的春天。'});
  const profileFields={name:'Name',nickname:'Nickname',species:'Species',breed:'Breed',sex:'Sex',coatColor:'CoatColor',birthday:'Birthday',birthPlace:'BirthPlace',adoptedAt:'AdoptedAt',personality:'Personality',favoriteThings:'FavoriteThings',notes:'Notes',subtitle:'Subtitle'};
  let profileDirty=false, draftAvatar="", profileUploadBusy=false;
  let currentView='home', editingId=null, editingType='growth', selected=[], busy=false, activeId=null, pendingImport=null, toastTimer;
  const captions=['蜷成小小一团','陪你躺一会儿','安静地看世界','是你呀','靠近一点点','伸一个大懒腰'];
  const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  const localDate=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
  const niceDate=s=>{const [y,m,d]=s.split('-');return y+' 年 '+Number(m)+' 月 '+Number(d)+' 日';};
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
  function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
  function storageError(e){if(e?.name==='QuotaExceededError')return '本机存储空间不足，未保存。请先导出备份，再清理空间或减少附件。';return '无法保存到浏览器。请关闭无痕模式，检查浏览器是否允许本地存储。原记录没有被删除。';}
  function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('her-memory-book-public-v1',1);r.onupgradeneeded=()=>{r.result.createObjectStore('records',{keyPath:'id'});r.result.createObjectStore('settings',{keyPath:'key'});};r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('请关闭其他正在使用纪念册的窗口，再重新打开。'));r.onsuccess=()=>resolve(r.result);});}
  function transaction(stores,mode,action){return new Promise((resolve,reject)=>{let result;const tx=db.transaction(stores,mode);tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('保存已中止'));try{action(tx,v=>{result=v});}catch(e){tx.abort();reject(e);}});}
  async function refresh(){const all=await transaction(['records','settings'],'readonly',(tx,result)=>{const r=tx.objectStore('records').getAll(),p=tx.objectStore('settings').get('profile');const data={};r.onsuccess=()=>{data.records=r.result;result(data)};p.onsuccess=()=>{data.profile=p.result?.value;result(data)};});records=all.records;if(all.profile)pet=C.profile(all.profile);render();}
  async function putRecord(r){await transaction(['records'],'readwrite',tx=>tx.objectStore('records').put(r));await refresh();}
  function setView(value){currentView=['home','profile','growth','memory'].includes(value)?value:'home';for(const name of ['home','profile','growth','memory'])$('#'+name+'View').hidden=name!==currentView;document.querySelectorAll('.header [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===currentView);if(b.dataset.view===currentView)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(location.hash!=='#'+currentView)history.replaceState(null,'','#'+currentView);renderLists();}
  function makeMedia(m,cls='',controls=false){const el=node(m.mime.startsWith('video/')?'video':'img',cls);el.src=m.data;if(el.tagName==='IMG'){el.alt=m.name;el.loading='lazy';}else{el.controls=controls;el.preload=controls?'metadata':'none';el.playsInline=true;if(!controls)el.muted=true;}return el;}
  function empty(container,type,filtered){const wrap=node('div','empty-state');wrap.append(node('span','empty-leaf','❧'),node('h2','',filtered?'这一页，还没有找到记录':type==='growth'?'从她的某一天开始':'把一个暖暖的片刻留在这里'),node('p','',filtered?'试试其他月份，或清除搜索条件。':type==='growth'?'选一个日期，写下当时的体重、模样和小事。':'不需要很长的故事，一句话、一张照片就很好。'));if(!filtered){const b=node('button','button primary',type==='growth'?'＋ 添加第一条成长记录':'＋ 收藏第一个片刻');b.onclick=()=>openEditor(type);wrap.append(b);}container.append(wrap);}
  function openButton(r,text='展开这一刻 →'){const b=node('button','text-button',text);b.onclick=()=>showRecord(r.id);return b;}
  function growthCard(r){const item=node('article','timeline-item'),time=node('time','timeline-date');time.dateTime=r.date;time.append(node('strong','',Number(r.date.slice(5,7))+' 月 '+Number(r.date.slice(8))+' 日'),node('span','',r.date.slice(0,4)));const card=node('div','record-card'),top=node('div','record-top');top.append(node('h2','',r.title));if(r.weight!==null)top.append(node('span','weight-tag',r.weight+' kg'));card.append(top);if(r.notes)card.append(node('p','',r.notes.length>180?r.notes.slice(0,180)+'…':r.notes));if(r.media.length){const media=node('div','card-media');r.media.slice(0,3).forEach(m=>{const b=node('button','media-thumb');b.setAttribute('aria-label','查看 '+r.title+' 的附件');b.append(makeMedia(m));if(m.mime.startsWith('video/'))b.append(node('span','play-tag','▶ 视频'));b.onclick=()=>showRecord(r.id);media.append(b);});card.append(media);}const end=node('div','card-end');end.append(node('span','',r.media.length?r.media.length+' 份照片 / 视频':'文字记录'),openButton(r));card.append(end);item.append(time,card);return item;}
  function memoryCard(r){const item=node('article','memory-card'),cover=node('button','memory-cover');cover.setAttribute('aria-label','打开回忆：'+r.title);cover.onclick=()=>showRecord(r.id);if(r.media.length){cover.append(makeMedia(r.media[0]));if(r.media[0].mime.startsWith('video/'))cover.append(node('span','play-tag','▶ 视频'));}else{cover.classList.add('no-photo');cover.textContent='❦';}const body=node('div','memory-body'),time=node('time','',r.date.replaceAll('-',' . '));time.dateTime=r.date;body.append(time,node('h2','',r.title));if(r.notes)body.append(node('p','',r.notes.length>90?r.notes.slice(0,90)+'…':r.notes));const end=node('div','card-end');end.append(node('span','',r.media.length?r.media.length+' 份珍藏':'一段小小的故事'),openButton(r,'翻开 →'));body.append(end);item.append(cover,body);return item;}
  function renderLists(){for(const type of ['growth','memory']){const box=$('#'+type+'List');box.replaceChildren();const opts={type,month:$('#'+type+'Month').value,query:$('#'+type+'Search').value,ascending:$('#'+type+'Order').value==='asc'};const rows=C.select(records,opts);if(!rows.length)empty(box,type,!!(opts.month||opts.query));else rows.forEach(r=>box.append(type==='growth'?growthCard(r):memoryCard(r)));if(type==='growth'){const weighted=rows.filter(r=>r.weight!==null).sort((a,b)=>b.date.localeCompare(a.date));const summary=$('#weightSummary');summary.hidden=!weighted.length;summary.replaceChildren();if(weighted.length)summary.append(node('span','','当前筛选中的最近体重'),node('strong','',weighted[0].weight+' kg'),node('span','',niceDate(weighted[0].date)),node('span','','仅记录体重，不作健康判断。'));}}}
  function render(){const gc=records.filter(r=>r.type==='growth').length,mc=records.filter(r=>r.type==='memory').length;$('#growthCount').textContent=gc?'已珍藏 '+gc+' 个成长时刻':'翻开属于她的成长日记';$('#memoryCount').textContent=mc?'已珍藏 '+mc+' 个暖心片刻':'收好那些不想忘记的小事';$('#petName').textContent=pet.name;$('#dedication').textContent=pet.subtitle;$('#saveState').textContent='本机纪念册 · '+records.length+' 条记录';renderProfile();renderLists();}
  function fillProfileForm(){draftAvatar=pet.avatar||'';$('#avatarPreview').src=draftAvatar||HER_PLACEHOLDER;for(const [key,suffix] of Object.entries(profileFields))$('#profile'+suffix).value=pet[key]||'';document.querySelectorAll('[name="portraitIndex"]').forEach(r=>r.checked=Number(r.value)===pet.portraitIndex);profileDirty=false;$('#profileError').textContent='';}
  function renderProfile(){
    const portrait=pet.avatar?{data:pet.avatar}:HER_SEED[pet.portraitIndex??3]||{data:HER_PLACEHOLDER};$('#heroPhoto').src=portrait.data;$('#profilePhoto').src=portrait.data;$('#profilePhoto').alt=pet.name+'的档案照片';$('#heroPhoto').alt=pet.avatar?pet.name+'的照片':'植物花园装饰，尚未上传宠物照片';$('.portrait-caption strong').textContent=pet.avatar?'是你呀。':'把你的照片，放在这里';
    $('#passportName').textContent=pet.name;$('#passportNickname').textContent=pet.nickname?'也叫 '+pet.nickname:'一位独一无二的小伙伴';$('#passportMessage').textContent=pet.subtitle;
    const facts=[['种类 / 品种',[pet.species,pet.breed].filter(Boolean).join(' · ')],['性别',{female:'女孩',male:'男孩',unknown:'不确定'}[pet.sex]],['出生日期',pet.birthday?niceDate(pet.birthday):''],['出生地点',pet.birthPlace],['到家日期',pet.adoptedAt?niceDate(pet.adoptedAt):''],['毛色',pet.coatColor]];
    const dl=$('#passportFacts');dl.replaceChildren();for(const [label,value] of facts){const row=node('div');row.append(node('dt','',label),node('dd','',value||'待你补充'));dl.append(row);}if(!profileDirty)fillProfileForm();
  }
  function editorLock(value){busy=value;$('#saveRecord').disabled=value;$('#mediaInput').disabled=value;$('#editor').querySelectorAll('.remove-media,.reference-picker button,[data-close]').forEach(b=>b.disabled=value);$('#uploadStatus').textContent=value?'正在处理，请稍等…':'保存后可随时修改。';}
  function openEditor(type,id=null){if(!db){toast('纪念册存储尚未就绪，请查看页面上方提示。');return;}editingType=type;editingId=id;const r=id?records.find(r=>r.id===id):null;selected=r?[...r.media]:[];$('#recordForm').reset();$('#recordDate').value=r?.date||localDate();$('#recordTitle').value=r?.title||'';$('#recordNotes').value=r?.notes||'';$('#recordWeight').value=r?.weight??'';$('#weightField').hidden=type!=='growth';$('#editorTitle').textContent=(id?'编辑':'')+(type==='growth'?'记下一天的成长':'收藏一个暖心片刻');$('#recordTitle').placeholder=type==='growth'?'小小的她，又长大了一点':'第一次把脑袋靠在我手心';$('#editorError').textContent='';editorLock(false);renderSelected();$('#editor').showModal();}
  function renderSelected(){const box=$('#selectedMedia');box.replaceChildren();selected.forEach((m,i)=>{const div=node('div','selected-item');div.append(makeMedia(m));const name=node('span','file-name',m.name);name.title=m.name;const remove=node('button','remove-media','×');remove.type='button';remove.disabled=busy;remove.setAttribute('aria-label','移除 '+m.name);remove.onclick=()=>{selected.splice(i,1);renderSelected();};div.append(name,remove);box.append(div);});}
  function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('未能读取文件：'+file.name));reader.onabort=()=>reject(Error('文件读取已取消。'));reader.readAsDataURL(file);});}
  $('#mediaInput').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;$('#editorError').textContent='';try{if(files.length+selected.length>12)throw Error('每条记录最多 12 个附件，请分成多条记录。');let total=selected.reduce((s,m)=>s+m.data.length*.75,0);for(const f of files){if(!C.MIME.test(f.type))throw Error('不支持 '+f.name+' 的格式。请使用 JPG、PNG、WebP、GIF、MP4、WebM 或 MOV。');if(f.size>C.MAX_FILE)throw Error(f.name+' 超过 50 MB，请先压缩或截短。');total+=f.size;}if(total>C.MAX_TOTAL)throw Error('一条记录的附件合计不能超过 160 MB。');editorLock(true);const added=[];for(const f of files)added.push({name:f.name,mime:f.type,data:await readFile(f)});selected.push(...added);renderSelected();}catch(err){$('#editorError').textContent=err.message;}finally{editorLock(false);e.target.value='';}});
  $('#recordForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;$('#editorError').textContent='';let r;try{const old=records.find(r=>r.id===editingId),now=new Date().toISOString();r=C.validateRecord({id:editingId||uid(),type:editingType,date:$('#recordDate').value,title:$('#recordTitle').value,notes:$('#recordNotes').value,weight:editingType==='growth'&&$('#recordWeight').value!==''?Number($('#recordWeight').value):null,media:selected,createdAt:old?.createdAt||now,updatedAt:now});}catch(err){$('#editorError').textContent=err.message;return;}editorLock(true);try{await putRecord(r);$('#editor').close();$('#'+editingType+'Month').value='';$('#'+editingType+'Search').value='';setView(editingType);toast('这一刻，已经好好收进纪念册。');}catch(err){$('#editorError').textContent=storageError(err);}finally{editorLock(false);}});
  function fillDetail(media){const box=$('#detailMedia');box.replaceChildren();media.forEach(m=>{const figure=node('figure');const el=makeMedia(m,'',true);figure.append(el);const caption=node('figcaption','',m.name);figure.append(caption);if(m.mime.startsWith('video/')){const link=node('a','','下载原视频');link.href=m.data;link.download=m.name;figure.append(link);el.addEventListener('error',()=>{caption.textContent=m.name+' · 当前浏览器无法播放此编码，可下载原视频查看。';});}box.append(figure);});}
  function showRecord(id){const r=records.find(x=>x.id===id);if(!r)return;activeId=id;$('#detailDate').textContent=niceDate(r.date)+(r.type==='growth'?' · 成长记录':' · 暖心回忆');$('#detailTitle').textContent=r.title;$('#detailNotes').textContent=r.notes;$('#detailWeight').hidden=r.weight===null;$('#detailWeight').textContent=r.weight===null?'':r.weight+' kg';$('#detailActions').hidden=false;fillDetail(r.media);$('#detail').showModal();}
  $('#editRecord').onclick=()=>{const r=records.find(x=>x.id===activeId);if(r){$('#detail').close();openEditor(r.type,r.id);}};
  $('#deleteRecord').onclick=()=>$('#confirmDialog').showModal();
  $('#confirmDelete').onclick=async()=>{const id=activeId;$('#confirmDelete').disabled=true;try{await transaction(['records'],'readwrite',tx=>tx.objectStore('records').delete(id));await refresh();$('#confirmDialog').close();$('#detail').close();toast('这条记录已删除。');}catch(e){toast(storageError(e));}finally{$('#confirmDelete').disabled=false;}};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
  document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>{d.querySelectorAll('video').forEach(v=>v.pause());if(d.id==='detail')$('#detailMedia').replaceChildren();});});
  $('#editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
  document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openEditor(b.dataset.add));
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setView(b.dataset.view);window.scrollTo({top:0,behavior:'instant'});});
  window.addEventListener('hashchange',()=>setView(location.hash.slice(1)));
  for(const type of ['growth','memory']){for(const suffix of ['Month','Search','Order'])$('#'+type+suffix).addEventListener(suffix==='Search'?'input':'change',renderLists);$('#'+type+'Clear').onclick=()=>{$('#'+type+'Month').value='';$('#'+type+'Search').value='';renderLists();};}
  $('#heroPhoto').src=HER_PLACEHOLDER;$('.originals').hidden=!HER_SEED.length;$('#referencePicker').closest('details').hidden=!HER_SEED.length;$('#profilePortraitPicker').hidden=!HER_SEED.length;
  HER_SEED.forEach((m,i)=>{const button=node('button','original-item');button.append(makeMedia(m),node('span','',captions[i]));button.setAttribute('aria-label','查看原始照片：'+captions[i]);button.onclick=()=>{activeId=null;$('#detailDate').textContent='最初的照片 · 日期待补充';$('#detailTitle').textContent=captions[i];$('#detailNotes').textContent='添加成长记录或暖心回忆时，可以选用这张照片。';$('#detailWeight').hidden=true;$('#detailActions').hidden=true;fillDetail([m]);$('#detail').showModal();};$('#originalGrid').append(button);const pick=node('button');pick.type='button';pick.append(makeMedia(m));pick.setAttribute('aria-label','添加照片：'+captions[i]);pick.onclick=()=>{if(selected.length>=12){$('#editorError').textContent='每条记录最多 12 个附件。';return;}selected.push(m);renderSelected();toast('照片已加入这一刻。');};$('#referencePicker').append(pick);});
  HER_SEED.forEach((m,i)=>{const label=node('label');const radio=node('input');radio.type='radio';radio.name='portraitIndex';radio.value=String(i);radio.checked=i===3;const image=makeMedia(m);image.alt='档案照片 '+(i+1)+'：'+captions[i];label.append(radio,image,node('span','',captions[i]));$('#profilePortraitPicker').append(label);});
  $('#profileForm').addEventListener('input',()=>{profileDirty=true;$('#profileSaveStatus').textContent='有未保存的修改，记得点击“保存宠物档案”。';});
  $('#profileForm').addEventListener('change',()=>{profileDirty=true;$('#profileSaveStatus').textContent='有未保存的修改，记得点击“保存宠物档案”。';});
  $('#avatarInput').addEventListener('change',async e=>{
    const f=e.target.files[0];if(!f)return;
    $('#profileError').textContent='';profileUploadBusy=true;$('#saveProfile').disabled=true;$('#resetProfile').disabled=true;$('#removeAvatar').disabled=true;
    try{if(!/^image\/(jpeg|png|webp|gif)$/.test(f.type)||f.size>8*1024*1024)throw Error('请选择不超过 8 MB 的 JPG、PNG、WebP 或 GIF 照片。');draftAvatar=await readFile(f);$('#avatarPreview').src=draftAvatar;profileDirty=true;$('#profileSaveStatus').textContent='照片已选择，点击保存宠物档案后生效。';}
    catch(err){$('#profileError').textContent=err.message;}
    finally{profileUploadBusy=false;$('#saveProfile').disabled=false;$('#resetProfile').disabled=false;$('#removeAvatar').disabled=false;e.target.value='';}
  });
  $('#removeAvatar').onclick=()=>{draftAvatar='';$('#avatarPreview').src=HER_PLACEHOLDER;profileDirty=true;$('#profileSaveStatus').textContent='照片已移除，保存后生效。';};
  $('#resetProfile').onclick=()=>{fillProfileForm();$('#profileSaveStatus').textContent='已恢复为上次保存的档案。';};
  $('#settingsButton').onclick=()=>$('#settings').showModal();
  $('#settingsProfileLink').onclick=()=>{$('#settings').close();setView('profile');window.scrollTo({top:0,behavior:'instant'});};
  $('#profileForm').addEventListener('submit',async e=>{
    e.preventDefault();if(profileUploadBusy)return;if(!db){$('#profileError').textContent='本地存储不可用，档案尚未保存。';return;}
    let p;try{const input={};for(const [key,suffix] of Object.entries(profileFields))input[key]=$('#profile'+suffix).value;input.avatar=draftAvatar;input.portraitIndex=Number($('[name="portraitIndex"]:checked')?.value??3);p=C.profile(input);}catch(err){$('#profileError').textContent=err.message;return;}
    const controls=[...$('#profileForm').elements];controls.forEach(c=>c.disabled=true);$('#profileError').textContent='';
    try{await transaction(['settings'],'readwrite',tx=>tx.objectStore('settings').put({key:'profile',value:p}));pet=p;profileDirty=false;render();$('#profileSaveStatus').textContent='宠物档案已保存在本机。导出备份时会一起收好。';toast('她的小档案，已经好好收好了。');}
    catch(err){$('#profileError').textContent=storageError(err);}
    finally{controls.forEach(c=>c.disabled=false);}
  });
  $('#exportButton').onclick=async()=>{if(!db){$('#backupStatus').textContent='本地存储不可用，无法读取备份。';return;}$('#exportButton').disabled=true;$('#backupStatus').textContent='正在整理照片和视频…';try{await refresh();const json=JSON.stringify({format:'her-memory-book',version:3,exportedAt:new Date().toISOString(),profile:pet,records});const blob=new Blob([json],{type:'application/json'});const url=URL.createObjectURL(blob);const a=node('a');a.href=url;a.download='她还在这里-纪念册备份-'+localDate()+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);$('#backupStatus').textContent='已生成 '+records.length+' 条记录的备份并请求下载，请确认文件已保存。备份已包含档案照片和记录附件。';}catch(e){$('#backupStatus').textContent='备份未完成：'+e.message;}finally{$('#exportButton').disabled=false;}};
  $('#importInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;$('#importPreview').hidden=true;pendingImport=null;$('#backupStatus').textContent='正在检查备份…';try{if(f.size>512*1024*1024)throw Error('备份超过 512 MB，当前版本无法安全读取。');pendingImport=C.backup(JSON.parse(await f.text()));const ids=new Set(records.map(r=>r.id)),fresh=pendingImport.records.filter(r=>!ids.has(r.id)).length;$('#importSummary').textContent='备份共有 '+pendingImport.records.length+' 条记录；新增 '+fresh+' 条，同编号的 '+(pendingImport.records.length-fresh)+' 条会跳过。';$('#restoreProfile').checked=false;$('#importPreview').hidden=false;$('#backupStatus').textContent='检查通过。确认后再写入本机纪念册。';}catch(err){$('#backupStatus').textContent='没有导入：'+err.message;}finally{e.target.value='';}});
  $('#cancelImport').onclick=()=>{pendingImport=null;$('#importPreview').hidden=true;$('#backupStatus').textContent='已取消导入。';};
  $('#confirmImport').onclick=async()=>{if(!pendingImport||!db)return;$('#confirmImport').disabled=true;try{const pack=pendingImport;let added=0;await transaction(['records','settings'],'readwrite',tx=>{const store=tx.objectStore('records');for(const r of pack.records){const lookup=store.get(r.id);lookup.onsuccess=()=>{if(!lookup.result){store.add(r);added++;}};}if($('#restoreProfile').checked)tx.objectStore('settings').put({key:'profile',value:pack.profile});});if($("#restoreProfile").checked)profileDirty=false;await refresh();pendingImport=null;$('#importPreview').hidden=true;$('#backupStatus').textContent='已导入 '+added+' 条新记录，原有记录已保留。';toast('回忆已收好。');}catch(e){$('#backupStatus').textContent=storageError(e);}finally{$('#confirmImport').disabled=false;}};
  async function init(){setView(location.hash.slice(1));try{db=await openDB();db.onversionchange=()=>{db.close();db=null;$('#storageWarning').hidden=false;$('#storageWarning').textContent='纪念册存储发生变化，请重新打开页面后再编辑。';};await refresh();}catch(e){db=null;$('#storageWarning').textContent='本地存储未能打开：'+e.message+'。目前可以看照片，但不能保存记录。请用普通窗口中的 Edge 或 Chrome 打开。';$('#storageWarning').hidden=false;$('#saveState').textContent='存储不可用 · 未保存';}}
  init();
})();
